name: ruff
on:
  push:
    branches: main
    paths:
      - '**.py'
      - .github/workflows/ruff.yml
      - 'requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/ruff.yml
      - 'requirements.txt'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'check --select I,F .'